### ISSUE TITLE
Class unavailable: DocumentScanner

### ISSUE THREAD

**Issue by MarvinKweyu** [onyonkaclifford/document-scanner#1]
@onyonkaclifford 
I can see that your test imports the document_scanner as below:

```py

from document_scanner import DocumentScanner
```

You, however, lack this file in your module. do you plan to include this?

**Comment by kli4d-o** [comment]
> @onyonkaclifford
>I can see that your test imports the document_scanner as below:
> 
> ```python
> from document_scanner import DocumentScanner
> ```
> 
> You, however, lack this file in your module. do you plan to include this?

Hello @MarvinKweyu, `DocumentScanner` is defined in `document_scanner/__init__.py`
